Change decl: kconf_id_lookup: remove "static"
   Won't build as is from tar.bz2 file complaining of,

ar: `u' modifier ignored since `D' is the default (see `U')
  CC       libs/parser/libs_parser_libkconfig_parser_la-yconf.lo
In file included from libs/parser/yconf.c:252:0:
libs/parser/hconf.gperf:153:1: error: conflicting types for ‘kconf_id_lookup’
libs/parser/hconf.gperf:12:31: note: previous declaration of ‘kconf_id_lookup’ was here
 static const struct kconf_id *kconf_id_lookup(register const char *str, register GPERF_LEN_TYPE len);
                               ^~~~~~~~~~~~~~~
Makefile:1404: recipe for target 'libs/parser/libs_parser_libkconfig_parser_la-yconf.lo' failed
make[1]: *** [libs/parser/libs_parser_libkconfig_parser_la-yconf.lo] Error 1
Makefile:889: recipe for target 'all' failed
make: *** [all] Error 2

Change-Id: Idb8a9a1ee2c548b9bb20f16a1e3a40e870ce5960